Update 3.yml

diff --git a/.github/workflows/3.yml b/.github/workflows/3.yml
--- a/.github/workflows/3.yml
+++ b/.github/workflows/3.yml
@@ -1,78 +1,75 @@
- name: allure-junit5-maven
+#  name: allure-junit5-maven
 
- on: [ push ]
+#  on: [ push ]
 
- env:
-   COUNT: Monday
+#  env:
+#    COUNT: Monday
 
- jobs:
-   build:
-     runs-on: ubuntu-latest
-     steps:
-       - uses: actions/checkout@v3
+#  jobs:
+#    build:
+#      runs-on: ubuntu-latest
+#      steps:
+#        - uses: actions/checkout@v3
 
-       - name: Set up JDK 19
-         uses: actions/setup-java@v3
-         with:
-           java-version: '19'
-           distribution: 'temurin'
+#        - name: Set up JDK 19
+#          uses: actions/setup-java@v3
+#          with:
+#            java-version: '19'
+#            distribution: 'temurin'
 
-       - name: Run Test
-         if: always()
-         run: mvn clean test
-         continue-on-error: true
+#        - name: Run Test
+#          if: always()
+#          run: mvn clean test
+#          continue-on-error: true
          
-       - name: Get Allure history
-         uses: actions/checkout@v3
-         if: always()
-         continue-on-error: true
-         with:
-           ref: gh-pages
-           path: gh-pages
+#        - name: Get Allure history
+#          uses: actions/checkout@v3
+#          if: always()
+#          continue-on-error: true
+#          with:
+#            ref: gh-pages
+#            path: gh-pages
 
-       - name: Allure Report action from marketplace
-         uses: simple-elf/allure-report-action@master
-         if: always()
-         id: allure-report
-         with:
-           allure_results: allure-results
-           gh_pages: gh-pages
-           allure_report: allure-report
-           allure_history: allure-history
+#        - name: Allure Report action from marketplace
+#          uses: simple-elf/allure-report-action@master
+#          if: always()
+#          id: allure-report
+#          with:
+#            allure_results: allure-results
+#            gh_pages: gh-pages
+#            allure_report: allure-report
+#            allure_history: allure-history
 
-       - name: Deploy report to Github Pages
-         if: always()
-         uses: peaceiris/actions-gh-pages@v2
-         env:
-           PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-           PUBLISH_BRANCH: gh-pages
-           PUBLISH_DIR: allure-history
+#        - name: Deploy report to Github Pages
+#          if: always()
+#          uses: peaceiris/actions-gh-pages@v2
+#          env:
+#            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#            PUBLISH_BRANCH: gh-pages
+#            PUBLISH_DIR: allure-history
         
-       - name: "report"
-         id: report
-         uses: mikepenz/action-junit-report@v3
-         if: success() || failure()
-         with:
-           report_paths: '**/target/surefire-reports/TEST-*.xml'
+#        - name: "report"
+#          id: report
+#          uses: mikepenz/action-junit-report@v3
+#          if: success() || failure()
+#          with:
+#            report_paths: '**/target/surefire-reports/TEST-*.xml'
            
-       - name: 'zip'
-         uses: montudor/action-zip@v1
-         with:
-           args: zip qq -r allure-report.zip allure-report
-           
-       - name: 'print'
-         run: ls
+#        - name: 'zip'
+#          uses: montudor/action-zip@v1
+#          with:
+#            args: zip qq -r allure-report.zip allure-report
         
-       - name: Send email
-         uses: dawidd6/action-send-mail@v3
-         if: always()
-         with:
-           server_address: smtp.gmail.com
-           server_port: 465
-           username: ${{ secrets.EMAIL_USERNAME }}
-           password: ${{ secrets.EMAIL_PASSWORD }}
-           subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
-           body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }} <br> ALL TESTS COUNT IS "${{steps.report.outputs.total}}" FAILED TESTS IS "${{steps.report.outputs.failed}}" PASS TESTS IS "${{steps.report.outputs.passed}}"
-           to: ${{ secrets.EMAIL_USERNAME }}, on8d@yandex.ru
-           attachments: qq.zip
-           from: John Doe
+#        - name: Send email
+#          uses: dawidd6/action-send-mail@v3
+#          if: always()
+#          with:
+#            server_address: smtp.gmail.com
+#            server_port: 465
+#            username: ${{ secrets.EMAIL_USERNAME }}
+#            password: ${{ secrets.EMAIL_PASSWORD }}
+#            subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
+#            body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }} <br> ALL TESTS COUNT IS "${{steps.report.outputs.total}}" FAILED TESTS IS "${{steps.report.outputs.failed}}" PASS TESTS IS "${{steps.report.outputs.passed}}"
+#            to: ${{ secrets.EMAIL_USERNAME }}, on8d@yandex.ru
+#            attachments: qq.zip
+#            from: John Doe
