Update 4.yml

diff --git a/.github/workflows/4.yml b/.github/workflows/4.yml
--- a/.github/workflows/4.yml
+++ b/.github/workflows/4.yml
@@ -1,90 +1,90 @@
- name: allure-junit5-maven
+#  name: allure-junit5-maven
 
- on: [ push ]
+#  on: [ push ]
 
- jobs:
-   build:
-     runs-on: ubuntu-latest
-     steps:
-       - uses: actions/checkout@v3
+#  jobs:
+#    build:
+#      runs-on: ubuntu-latest
+#      steps:
+#        - uses: actions/checkout@v3
 
-       - name: Set up JDK 19
-         uses: actions/setup-java@v3
-         with:
-           java-version: '19'
-           distribution: 'temurin'
+#        - name: Set up JDK 19
+#          uses: actions/setup-java@v3
+#          with:
+#            java-version: '19'
+#            distribution: 'temurin'
 
-       - name: Run Test
-         if: always()
-         run: mvn clean test
-         continue-on-error: true
+#        - name: Run Test
+#          if: always()
+#          run: mvn clean test
+#          continue-on-error: true
          
-       - name: Get Allure history
-         uses: actions/checkout@v3
-         if: always()
-         continue-on-error: true
-         with:
-           ref: gh-pages
-           path: gh-pages
+#        - name: Get Allure history
+#          uses: actions/checkout@v3
+#          if: always()
+#          continue-on-error: true
+#          with:
+#            ref: gh-pages
+#            path: gh-pages
 
-       - name: Allure Report action from marketplace
-         uses: simple-elf/allure-report-action@master
-         if: always()
-         id: allure-report
-         with:
-           allure_results: allure-results
-           gh_pages: gh-pages
-           allure_report: allure-report
-           allure_history: allure-history
+#        - name: Allure Report action from marketplace
+#          uses: simple-elf/allure-report-action@master
+#          if: always()
+#          id: allure-report
+#          with:
+#            allure_results: allure-results
+#            gh_pages: gh-pages
+#            allure_report: allure-report
+#            allure_history: allure-history
 
-       - name: Deploy report to Github Pages
-         if: always()
-         uses: peaceiris/actions-gh-pages@v2
-         env:
-           PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-           PUBLISH_BRANCH: gh-pages
-           PUBLISH_DIR: allure-history
+#        - name: Deploy report to Github Pages
+#          if: always()
+#          uses: peaceiris/actions-gh-pages@v2
+#          env:
+#            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#            PUBLISH_BRANCH: gh-pages
+#            PUBLISH_DIR: allure-history
         
-       - name: "report"
-         id: report
-         uses: mikepenz/action-junit-report@v3
-         if: success() || failure()
-         with:
-           report_paths: '**/target/surefire-reports/TEST-*.xml'
+#        - name: "report"
+#          id: report
+#          uses: mikepenz/action-junit-report@v3
+#          if: success() || failure()
+#          with:
+#            report_paths: '**/target/surefire-reports/TEST-*.xml'
            
-       - name: Upload Artifact 
-         id: upload
-         uses: actions/upload-artifact@v3
-         with: 
-           name: "allure-report-art"
-           path: allure-report
+#        - name: Upload Artifact 
+#          id: upload
+#          uses: actions/upload-artifact@v3
+#          with: 
+#            name: "allure-report-art"
+#            path: allure-report
            
-       - name: ls after upload
-         run: |
-           cd ./allure-report-art/
-           ls
+#        - name: ls after upload
+#          run: |
+#            cd ./allure-report-art/
+#            ls
          
-       - name: dowlload
-         id: dowlload
-         uses: actions/download-artifact@v3
-         with:
-           name: allure-report-art
-#            path: allure-report-art
+#        - name: dowlload
+#          id: dowlload
+#          uses: actions/download-artifact@v3
+#          with:
+#            name: allure-report-art
+# #            path: allure-report-art
         
-       - name: ls after dowload
-         run: ls
+#        - name: ls after dowload
+#          run: ls
         
-       - name: Send email
-         uses: dawidd6/action-send-mail@v3
-         if: always()
-         with:
-           server_address: smtp.gmail.com
-           server_port: 465
-           username: ${{ secrets.EMAIL_USERNAME }}
-           password: ${{ secrets.EMAIL_PASSWORD }}
-           subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
-           html_body:  FROM GITHUB ACTIONS <br> PROJECT IS ${{ github.repository }} ${{ github.job }} <br> WORKFLOW IS ${{ github.workflow }} <br> STATUS IS <b> ${{ job.status }} </b> <br> ALL TESTS COUNT IS <b> "${{steps.report.outputs.total}}" </b> <br> FAILED TESTS IS <b> "${{steps.report.outputs.failed}}" </b> <br> PASS TESTS IS <b> "${{steps.report.outputs.passed}}" </b> <br> LINK TO ARTIFACT https://github.com/${{ github.repository }}/blob/${{ github.ref }}/artifacts/my_artifact.zip
-           to: ${{ secrets.EMAIL_USERNAME }}, ${{ secrets.EMAIL_USERNAME2 }}
-           attachments: "allure-report-art"
-           convert_markdown: true
-           from: John Doe
+#        - name: Send email
+#          uses: dawidd6/action-send-mail@v3
+#          if: always()
+#          with:
+#            server_address: smtp.gmail.com
+#            server_port: 465
+#            username: ${{ secrets.EMAIL_USERNAME }}
+#            password: ${{ secrets.EMAIL_PASSWORD }}
+#            subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
+#            html_body:  FROM GITHUB ACTIONS <br> PROJECT IS ${{ github.repository }} ${{ github.job }} <br> WORKFLOW IS ${{ github.workflow }} <br> STATUS IS <b> ${{ job.status }} </b> <br> ALL TESTS COUNT IS <b> "${{steps.report.outputs.total}}" </b> <br> FAILED TESTS IS <b> "${{steps.report.outputs.failed}}" </b> <br> PASS TESTS IS <b> "${{steps.report.outputs.passed}}" </b> <br> LINK TO ARTIFACT https://github.com/${{ github.repository }}/blob/${{ github.ref }}/artifacts/my_artifact.zip
+#            to: ${{ secrets.EMAIL_USERNAME }}, ${{ secrets.EMAIL_USERNAME2 }}
+#            attachments: "allure-report-art"
+#            convert_markdown: true
+#            from: John Doe
